"""
Plot air pressure and density vs altitude from the 1976 U.S. Standard
Atmosphere, in the house plot style used for the photolysis figures.

Data: data/us_standard_atmosphere_1976.csv
    (generated by generate_us_standard_atmosphere.py)

Requires: pandas, matplotlib
    pip install pandas matplotlib

Run:
    python plot_pressure_density_profile.py
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from _plot_style import LINEWIDTH, FONTSIZE, TITLE_FONTSIZE, COLORS, apply_style

# Fraction of the atmosphere's mass lying above a given pressure level
# equals (1 - P/P0), since pressure is just the weight of overlying air.
PERCENTILES = [0.50, 0.90, 0.99, 0.999]
P0_HPA = 1013.25

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
FIGURES_DIR = REPO_ROOT / "assets" / "figures"


def main():
    df = pd.read_csv(DATA_DIR / "us_standard_atmosphere_1976.csv")
    altitude_km = df.altitude_km.to_numpy()
    pressure_hPa = df.pressure_Pa.to_numpy() / 100.0
    density = df.density_kg_m3.to_numpy()

    apply_style()
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9, 4), sharey=True)

    ax1.plot(pressure_hPa, altitude_km, color=COLORS[0], lw=LINEWIDTH)
    ax1.set_xlabel("Air pressure (hPa)", fontsize=FONTSIZE)
    ax1.set_ylabel("Altitude (km)", fontsize=FONTSIZE)
    ax1.tick_params(labelsize=FONTSIZE - 1)
    ax1.set_xlim(0, 1050)
    ax1.set_ylim(0, altitude_km.max())

    # Mark the altitudes above which 50%, 90%, 99% and 99.9% of the
    # atmosphere's mass lies (i.e. where pressure has dropped to that
    # fraction of the surface value).
    pressure_ascending = pressure_hPa[::-1]
    altitude_ascending = altitude_km[::-1]
    for frac in PERCENTILES:
        p_level = (1 - frac) * P0_HPA
        alt_level = np.interp(p_level, pressure_ascending, altitude_ascending)
        ax1.plot(p_level, alt_level, "o", color=COLORS[1], markersize=4)
        ax1.annotate(
            f"{frac * 100:g}%",
            xy=(p_level, alt_level),
            xytext=(p_level + 60, alt_level),
            fontsize=FONTSIZE - 3,
            color=COLORS[1],
            va="center",
        )

    ax2.plot(density, altitude_km, color=COLORS[0], lw=LINEWIDTH)
    ax2.set_xlabel("Air density (kg m$^{-3}$)", fontsize=FONTSIZE)
    ax2.tick_params(labelsize=FONTSIZE - 1)
    ax2.set_xlim(0, 1.3)

    fig.suptitle("1976 U.S. Standard Atmosphere", fontsize=TITLE_FONTSIZE)
    fig.tight_layout()
    fig.savefig(FIGURES_DIR / "m1-fig1-3-pressure-density.png", dpi=150)
    print("Saved plot to m1-fig1-3-pressure-density.png")


if __name__ == "__main__":
    main()
